---
- name: Directory management
  hosts: docker_nodes
  become: true

  tasks:
    - name: Create app directory
      file:
        path: /opt/myapp
        state: directory
        mode: '0755'
---
- name: Remove temp directory
  file:
    path: /tmp/oldstuff
    state: absent
